import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import HeaderSection from "@/components/home/Header";
import Footer from "@/components/home/Footer";
import { defaultSEO } from "@/lib/seo";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = defaultSEO;

// : Metadata = {
//   title: "Supreme Coach",
//   // title: "Shahid",
//   description: "Generated by create next app",
//   icons: {
//     icon: "/logos/s coach fav 2.svg",
//   },
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <HeaderSection />
        {children}
        <Footer />
      </body>
    </html>
  );
}
